apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  namespace: {{ .Values.configmap.namespace }}
data:
  data-prepper-config.yaml: |
    ssl: false
  otel-v1-apm-span-index-standard-template.json: |
{{ tpl (.Files.Get "files/otel-v1-apm-span-index-standard-template.json") . | indent 4 }}
  pipelines.yaml: |
{{ tpl (.Files.Get "files/pipelines.yaml") . | indent 4 }}
